rope = 0;
color = c_white;
lightSize = 799;
targetX = 0;
targetY = 0;
followDirectionX = 0;
followDirectionY = 0;
target = oPlayer;
state = oGlowbieFollowState;
imageIndex = GlowbieBlue;
//object_set_sprite(oGlowbie, spriteImage);